version: '3.8'

services:
  backend:
    build:
      context: ../incident-manager-backend  # from backend 
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../incident-manager-frontend  # from frontend 
    ports:
      - "3000:80"  # Nginx 80 port match to host 3000 port
